name: 🗑️ Clean Workflow Runs

on:
  schedule:
    - cron: "0 16 * * 1" # Runs "At 00:00 UTC+8, Monday" (00:00 Beijing Time). https://crontab.guru/

  workflow_dispatch:
    inputs:
      runs_older_than:
        description: "The amount of days old to delete"
        default: "21"
        required: false
      runs_to_keep:
        description: "The amount of latest workflow runs to keep"
        default: "0"
        required: false
      dry_run:
        description: "Only show what would be deleted (dry run)"
        type: boolean
        default: true
        required: false

env:
  SCHEDULED_RUNS_OLDER_THAN: "21"
  SCHEDULED_RUNS_TO_KEEP: "0"

jobs:
  clean-logs:
    name: Clean Up Workflow Logs
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      # - uses: igorjs/gh-actions-clean-workflow@v6
      - uses: diverger/gh-action-clean-workflow@main
        with:
          runs_older_than: ${{ github.event.inputs.runs_older_than || env.SCHEDULED_RUNS_OLDER_THAN }}
          runs_to_keep: ${{ github.event.inputs.runs_to_keep || env.SCHEDULED_RUNS_TO_KEEP }}
          dry_run: ${{ github.event.inputs.dry_run || 'false' }}
