name: Test OSS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-beijing
          bucket: diverger-github-linux-rockchip
          assets: |
            # This will upload all files in the .github directory to the /test/ directory in the OSS bucket
            ./.github/**:/test/
            # This will upload all files in the .github directory to the /test1/a directory in the OSS bucket, all files will be combined to a unopenable file, wrong use
            ./.github/**:/test1/a
            # Upload and rename the file to test2/test.yml in the OSS bucket
            ./.github/workflows/test-oss.yml:/test2/test.yml
            ./.github/workflows/test-oss.yml:/test3/test.oss.f.xyz.yml
            ./ubuntu-24.04-preinstalled-desktop-arm64-handy-hpd5kx.zip:/test4/ubuntu-24.04-preinstalled-desktop-arm64-handy-hpd5kx.zip
