name: Test OSS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-beijing
          bucket: diverger-github-linux-rockchip
          assets: |
            ./.github/**:/test1/a